version: '2'
services:
    db:
        build: mysql
        hostname: reddb
        container_name: reddb
        environment:
            MYSQL_ROOT_PASSWORD: password
        expose:
            - 3306
        volumes:
            - /APL/share:/APL/share
            - /mysql/data:/var/lib/mysql
    redmine:
        build:
            context: redmine
            args:
                HTTP_PROXY: ${HTTP_PROXY}
                HTTPS_PROXY: ${HTTPS_PROXY}
                http_proxy: ${http_proxy}
                https_proxy: ${https_proxy}
        hostname: redapp
        container_name: redapp
        environment:
            HTTP_PROXY: ""
            http_proxy: ""
            HTTPS_PROXY: ""
            https_proxy: ""
        volumes:
            - /APL/share:/APL/share
            - /APL/docker/redmine/var/www/redmine/plugins:/var/www/redmine/plugins
        ports:
            - 80:3000
        links:
            - db
            - mmsite
        command: bash -c 'while true; do sleep 10; done'
    mmsite:
        build:
            context: mattermost
            args:
                HTTP_PROXY: ${HTTP_PROXY}
                HTTPS_PROXY: ${HTTPS_PROXY}
                http_proxy: ${http_proxy}
                https_proxy: ${https_proxy}
        hostname: mmsite
        container_name: mmsite
        volumes:
            - /APL/share:/APL/share
            - /APL/docker/mmsite/usr/local/mattermost/config:/usr/local/mattermost/config
        ports:
            - 81:81
        links:
            - db
        #command: bash -c 'while true; do sleep 10; done'
