version: '2'
services:
    db:
        build: mysql
        hostname: reddb
        container_name: reddb
        environment:
            MYSQL_ROOT_PASSWORD: password
        expose:
            - 3306
        volumes:
            - /home/nwh/workspace/redmine-compose/mysql/create_redminedb.sql:/create_redminedb.sql
            - /APL/share:/APL/share
            - /APL/mysql/data:/var/lib/mysql
    redmine:
        build: redmine-debian
        hostname: redapp
        container_name: redapp
        volumes:
            - /APL/share:/APL/share
            - /APL/share/redmine/plugins:/var/www/redmine/plugins
        ports:
            - 82:3000
        links:
            - db
            - mmsite
        command: bash -c 'while true; do sleep 10; done'
    mmsite:
        build: mattermost
        hostname: mmsite
        container_name: mmsite
        volumes:
            - /APL/share:/APL/share
        ports:
            - 81:81
        links:
            - db
        command: bash -c 'while true; do sleep 10; done'
